title: "ra.VI"
description: "Repository Assistant with a Versatile Interface"
remote_theme: rundocs/jekyll-rtd-theme

markdown: kramdown

plugins:
- jemoji
- jekyll-avatar
- jekyll-mentions

kramdown:
  auto_ids: true

translate:
  # shortcodes
  danger:
  note:
  tip:
  warning:
  # 404
  not_found:
  # copyright
  revision:
  # search
  searching:
  search:
  search_docs:
  search_results:
  search_results_found: # the "#" in this translate will replaced with results size!
  search_results_not_found:
